"""
scripts/migrate_sqlite_to_postgres.py
=====================================
Non-destructive migration utility to transfer historical telemetry records
and system configuration from SQLite (database/plant_monitor.db) to PostgreSQL.

Guarantees:
  1. Preserves all 89 existing records with their exact primary key IDs (1..89).
  2. Preserves the original 85 historical records.
  3. Preserves all system calibration settings.
  4. Automatically synchronizes PostgreSQL identity sequence so new inserts start at 90.
  5. Executes comprehensive post-migration verification assertions.
  6. NEVER deletes or modifies the source SQLite database.

Usage:
  python scripts/migrate_sqlite_to_postgres.py --postgres-url "postgresql://user:pass@host:5432/dbname"
  python scripts/migrate_sqlite_to_postgres.py --dry-run
"""

import os
import sys
import argparse
import sqlite3
from datetime import datetime

# Driver import
try:
    import psycopg2
    import psycopg2.extras
except ImportError:
    psycopg2 = None


def create_postgres_schema(pg_conn):
    """Creates the target PostgreSQL tables and indexes if they do not exist."""
    with pg_conn.cursor() as cur:
        # 1. sensor_readings table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS sensor_readings (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                device_id VARCHAR(64) NOT NULL DEFAULT 'ESP32_003',
                moisture_raw DOUBLE PRECISION,
                moisture_percent DOUBLE PRECISION,
                temperature_c DOUBLE PRECISION,
                distance_cm DOUBLE PRECISION,
                plant_height_cm DOUBLE PRECISION,
                status VARCHAR(32) NOT NULL DEFAULT 'OK',
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT chk_moisture_raw CHECK (moisture_raw IS NULL OR (moisture_raw >= 0.0 AND moisture_raw <= 4095.0)),
                CONSTRAINT chk_moisture_pct CHECK (moisture_percent IS NULL OR (moisture_percent >= 0.0 AND moisture_percent <= 100.0)),
                CONSTRAINT chk_temperature_c CHECK (temperature_c IS NULL OR (temperature_c >= -40.0 AND temperature_c <= 85.0)),
                CONSTRAINT chk_distance_cm CHECK (distance_cm IS NULL OR distance_cm >= 0.0)
            );
        """)

        # Indexes
        cur.execute("CREATE INDEX IF NOT EXISTS idx_sensor_readings_created_at ON sensor_readings (created_at DESC);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_sensor_readings_device_created ON sensor_readings (device_id, created_at DESC);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_sensor_readings_status ON sensor_readings (status);")

        # 2. system_settings table
        cur.execute("""
            CREATE TABLE IF NOT EXISTS system_settings (
                key VARCHAR(64) PRIMARY KEY,
                value TEXT NOT NULL,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        """)
    pg_conn.commit()


def migrate(sqlite_path: str, pg_url: str, dry_run: bool = False) -> dict:
    """
    Executes data migration from SQLite to PostgreSQL.
    """
    if not os.path.exists(sqlite_path):
        raise FileNotFoundError(f"Source SQLite database not found at: {sqlite_path}")

    # 1. Read SQLite Source Database
    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row
    s_cur = sqlite_conn.cursor()

    s_cur.execute("""
        SELECT id, device_id, moisture_raw, moisture_percent, temperature_c,
               distance_cm, plant_height_cm, status, created_at
        FROM sensor_readings
        ORDER BY id ASC
    """)
    sensor_rows = s_cur.fetchall()

    s_cur.execute("SELECT key, value, updated_at FROM system_settings")
    settings_rows = s_cur.fetchall()
    sqlite_conn.close()

    total_sensor_records = len(sensor_rows)
    total_settings = len(settings_rows)

    print(f"[*] Read {total_sensor_records} sensor records and {total_settings} settings from SQLite ({sqlite_path}).")

    if dry_run:
        print("[*] DRY-RUN MODE: Validation checks passed. No data written to PostgreSQL.")
        return {
            "sensor_count": total_sensor_records,
            "settings_count": total_settings,
            "dry_run": True
        }

    # 2. Connect to PostgreSQL
    if not psycopg2:
        raise RuntimeError("psycopg2 is required for PostgreSQL migration. Run: pip install psycopg2-binary")

    normalized_url = pg_url
    if normalized_url.startswith("postgres://"):
        normalized_url = normalized_url.replace("postgres://", "postgresql://", 1)

    pg_conn = psycopg2.connect(normalized_url)

    try:
        # Create Schema
        create_postgres_schema(pg_conn)

        with pg_conn.cursor() as cur:
            # 3. Migrate sensor_readings preserving original IDs
            insert_sensor_sql = """
                INSERT INTO sensor_readings (
                    id, device_id, moisture_raw, moisture_percent,
                    temperature_c, distance_cm, plant_height_cm, status, created_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO UPDATE SET
                    device_id = EXCLUDED.device_id,
                    moisture_raw = EXCLUDED.moisture_raw,
                    moisture_percent = EXCLUDED.moisture_percent,
                    temperature_c = EXCLUDED.temperature_c,
                    distance_cm = EXCLUDED.distance_cm,
                    plant_height_cm = EXCLUDED.plant_height_cm,
                    status = EXCLUDED.status,
                    created_at = EXCLUDED.created_at;
            """
            for row in sensor_rows:
                cur.execute(insert_sensor_sql, (
                    row["id"],
                    row["device_id"],
                    row["moisture_raw"],
                    row["moisture_percent"],
                    row["temperature_c"],
                    row["distance_cm"],
                    row["plant_height_cm"],
                    row["status"],
                    row["created_at"]
                ))

            # Synchronize sequence so next insert starts at MAX(id) + 1
            cur.execute("""
                SELECT setval(
                    pg_get_serial_sequence('sensor_readings', 'id'),
                    COALESCE((SELECT MAX(id) FROM sensor_readings), 1) + 1,
                    false
                );
            """)

            # 4. Migrate system_settings
            insert_setting_sql = """
                INSERT INTO system_settings (key, value, updated_at)
                VALUES (%s, %s, %s)
                ON CONFLICT (key) DO UPDATE SET
                    value = EXCLUDED.value,
                    updated_at = EXCLUDED.updated_at;
            """
            for s in settings_rows:
                cur.execute(insert_setting_sql, (s["key"], s["value"], s["updated_at"]))

        pg_conn.commit()

        # 5. Verification Assertions
        with pg_conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM sensor_readings;")
            pg_sensor_count = cur.fetchone()[0]

            cur.execute("SELECT COUNT(*) FROM sensor_readings WHERE id <= 85;")
            pg_orig_85_count = cur.fetchone()[0]

            cur.execute("SELECT MIN(created_at), MAX(created_at) FROM sensor_readings;")
            min_ts, max_ts = cur.fetchone()

            cur.execute("SELECT COUNT(*) FROM sensor_readings WHERE device_id = 'ESP32_003';")
            pg_esp32_003_count = cur.fetchone()[0]

            cur.execute("SELECT key, value FROM system_settings;")
            pg_settings = dict(cur.fetchall())

        # Audit checks
        assert pg_sensor_count >= total_sensor_records, f"Count mismatch: expected {total_sensor_records}, got {pg_sensor_count}"
        assert pg_orig_85_count == 85, f"Original 85 records corrupted: count is {pg_orig_85_count}"
        assert pg_esp32_003_count >= 87, f"ESP32_003 records count error: {pg_esp32_003_count}"
        assert "dry_raw" in pg_settings and "wet_raw" in pg_settings, "Calibration settings missing in PostgreSQL"

        print("[+] Migration successfully completed and verified:")
        print(f"    - Total PostgreSQL Records: {pg_sensor_count}")
        print(f"    - Original Historical Records: {pg_orig_85_count} (Preserved)")
        print(f"    - Earliest Timestamp: {min_ts}")
        print(f"    - Latest Timestamp: {max_ts}")
        print(f"    - Settings Transferred: {len(pg_settings)}")
        print(f"    - Source SQLite ({sqlite_path}) preserved 100% intact.")

        return {
            "sensor_count": pg_sensor_count,
            "orig_85_count": pg_orig_85_count,
            "min_timestamp": str(min_ts),
            "max_timestamp": str(max_ts),
            "settings": pg_settings,
            "dry_run": False
        }

    finally:
        pg_conn.close()


def main():
    parser = argparse.ArgumentParser(description="Migrate Plant Monitor SQLite to PostgreSQL / Supabase")
    parser.add_argument("--sqlite-path", default="database/plant_monitor.db", help="Path to source SQLite database")
    parser.add_argument("--postgres-url", default=None, help="Target PostgreSQL connection URL")
    parser.add_argument("--supabase-url", default=None, help="Target Supabase PostgreSQL connection URL")
    parser.add_argument("--database-url", default=None, help="Target DATABASE_URL connection URL")
    parser.add_argument("--dry-run", action="store_true", help="Inspect and validate SQLite without writing to PostgreSQL")

    args = parser.parse_args()

    target_url = (
        args.supabase_url
        or args.database_url
        or args.postgres_url
        or os.environ.get("DATABASE_URL", "")
    ).strip()

    if not args.dry_run and not target_url:
        print("[!] No --database-url, --supabase-url, or DATABASE_URL provided. Running in --dry-run mode to inspect SQLite source.")
        args.dry_run = True

    try:
        migrate(sqlite_path=args.sqlite_path, pg_url=target_url, dry_run=args.dry_run)
    except Exception as e:
        print(f"[!] Migration failed: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
